apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ssh-${tenantname}-TF_REPLACE_REPOSITORY_HOST-TF_REPLACE_ORG_NAME-TF_REPLACE_NAME
  labels:
    toolkit.fluxcd.io/tenant: ${tenantname}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: tenant-repositories-ssh
    kind: SecretStore
  target:
    name: ssh-${tenantname}-TF_REPLACE_REPOSITORY_HOST-TF_REPLACE_ORG_NAME-TF_REPLACE_NAME
    deletionPolicy: "Delete"
    template:
      metadata:
        labels:
          toolkit.fluxcd.io/tenant: ${tenantname}
  data:
  - secretKey: identity
    remoteRef:
      key: tenants/${tenantnamespaceprefix}${tenantname}/repositories/TF_REPLACE_REPOSITORY_HOST/TF_REPLACE_ORG_NAME/TF_REPLACE_NAME/ssh/cd
      property: identity
  - secretKey: known_hosts
    remoteRef:
      key: tenants/${tenantnamespaceprefix}${tenantname}/repositories/TF_REPLACE_REPOSITORY_HOST/TF_REPLACE_ORG_NAME/TF_REPLACE_NAME/ssh/cd
      property: known_hosts
