github_org_name           = "pauwels-labs"
vault_address             = "https://secrets.pauwelslabs.com"
container_registry_domain = "274295908850.dkr.ecr.eu-west-1.amazonaws.com"
ci_webhook_domain         = "webhook.ci.pauwelslabs.com"
ecr_account_id            = "274295908850"
