cluster_account_id               = "140327370353"
cluster_account_assume_role_name = "OrganizationAccountAccessRole"
cluster_region                   = "eu-west-1"
remote_state_bucket_region       = "eu-west-1"
idp_url                          = "https://identity.pauwelslabs.com"
organisation_name                = "bitmantle"
environment_name                 = "prod"
