apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gitrepository-ecr-credentials-sync.yaml
- gotk-sync.yaml
- gotk-components.yaml
patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: helm-controller
      namespace: flux-system
    spec:
      template:
        spec:
          containers:
          - args:
            - --no-cross-namespace-refs=true
            - --default-service-account=default
            - --events-addr=http://notification-controller.flux-system.svc.cluster.local./
            - --watch-all-namespaces=true
            - --log-level=info
            - --log-encoding=json
            - --enable-leader-election
            name: manager
  target:
    kind: Deployment
    name: helm-controller
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: kustomize-controller
      namespace: flux-system
    spec:
      template:
        spec:
          containers:
          - args:
            - --no-cross-namespace-refs=true
            - --no-remote-bases=true 
            - --default-service-account=default
            - --events-addr=http://notification-controller.flux-system.svc.cluster.local./
            - --watch-all-namespaces=true
            - --log-level=info
            - --log-encoding=json
            - --enable-leader-election
            name: manager
  target:
    kind: Deployment
    name: kustomize-controller
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: notification-controller
      namespace: flux-system
    spec:
      template:
        spec:
          containers:
          - args:
            - --no-cross-namespace-refs=true
            - --watch-all-namespaces=true
            - --log-level=info
            - --log-encoding=json
            - --enable-leader-election
            name: manager
  target:
    kind: Deployment
    name: notification-controller
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: image-automation-controller
      namespace: flux-system
    spec:
      template:
        spec:
          containers:
          - image: 274295908850.dkr.ecr.eu-west-1.amazonaws.com/fluxcd/image-automation-controller:v0.34.1
            name: manager
  target:
    kind: Deployment
    name: image-automation-controller
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: image-reflector-controller
      namespace: flux-system
    spec:
      template:
        spec:
          containers:
          - image: 274295908850.dkr.ecr.eu-west-1.amazonaws.com/fluxcd/image-reflector-controller:v0.28.0
            name: manager
  target:
    kind: Deployment
    name: image-reflector-controller
- patch: |
    apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
    kind: Kustomization
    metadata:
      name: flux-system
      namespace: flux-system
    spec:
      serviceAccountName: kustomize-controller
  target:
    kind: Kustomization
    name: flux-system
- patch: |
    apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        istio.io/rev: stable
      name: flux-system
  target:
    kind: Namespace
    name: flux-system
