apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  secretRef:
    name: ssh-pauwels-labs-main-github-pauwels-labs-flux-infra
